//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MycobotCommunication
{
    [Serializable]
    public class SetFreshModeRequest : Message
    {
        public const string k_RosMessageName = "mycobot_communication/SetFreshMode";
        public override string RosMessageName => k_RosMessageName;

        public byte Status;

        public SetFreshModeRequest()
        {
            this.Status = 0;
        }

        public SetFreshModeRequest(byte Status)
        {
            this.Status = Status;
        }

        public static SetFreshModeRequest Deserialize(MessageDeserializer deserializer) => new SetFreshModeRequest(deserializer);

        private SetFreshModeRequest(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.Status);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.Status);
        }

        public override string ToString()
        {
            return "SetFreshModeRequest: " +
            "\nStatus: " + Status.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
