//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MycobotCommunication
{
    [Serializable]
    public class SetFreshModeResponse : Message
    {
        public const string k_RosMessageName = "mycobot_communication/SetFreshMode";
        public override string RosMessageName => k_RosMessageName;

        public bool Flag;

        public SetFreshModeResponse()
        {
            this.Flag = false;
        }

        public SetFreshModeResponse(bool Flag)
        {
            this.Flag = Flag;
        }

        public static SetFreshModeResponse Deserialize(MessageDeserializer deserializer) => new SetFreshModeResponse(deserializer);

        private SetFreshModeResponse(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.Flag);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.Flag);
        }

        public override string ToString()
        {
            return "SetFreshModeResponse: " +
            "\nFlag: " + Flag.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize, MessageSubtopic.Response);
        }
    }
}
