//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.MycobotUnity
{
    [Serializable]
    public class MyCobotTrackingTargetMsg : Message
    {
        public const string k_RosMessageName = "mycobot_unity/myCobotTrackingTarget";
        public override string RosMessageName => k_RosMessageName;

        public double[] joints;
        public Geometry.PoseMsg end_effector_pose;
        public Geometry.PoseMsg goal_pose;

        public MyCobotTrackingTargetMsg()
        {
            this.joints = new double[6];
            this.end_effector_pose = new Geometry.PoseMsg();
            this.goal_pose = new Geometry.PoseMsg();
        }

        public MyCobotTrackingTargetMsg(double[] joints, Geometry.PoseMsg end_effector_pose, Geometry.PoseMsg goal_pose)
        {
            this.joints = joints;
            this.end_effector_pose = end_effector_pose;
            this.goal_pose = goal_pose;
        }

        public static MyCobotTrackingTargetMsg Deserialize(MessageDeserializer deserializer) => new MyCobotTrackingTargetMsg(deserializer);

        private MyCobotTrackingTargetMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.joints, sizeof(double), 6);
            this.end_effector_pose = Geometry.PoseMsg.Deserialize(deserializer);
            this.goal_pose = Geometry.PoseMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.joints);
            serializer.Write(this.end_effector_pose);
            serializer.Write(this.goal_pose);
        }

        public override string ToString()
        {
            return "MyCobotTrackingTargetMsg: " +
            "\njoints: " + System.String.Join(", ", joints.ToList()) +
            "\nend_effector_pose: " + end_effector_pose.ToString() +
            "\ngoal_pose: " + goal_pose.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
